
services:
  rest-api:
    image: postgres:16-alpine
    container_name: task-03-session-management-db
    ports:
      - "5432:5432"
    
    
    environment:
       POSTGRES_USER: myuser
       POSTGRES_PASSWORD: mysecretpassword
       POSTGRES_DB: mydatabase

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

